name: pet_affinity
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  get_it: ^7.6.7
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.17
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  mobx_codegen: ^2.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/